---
- name: Install required packages
  apt: name={{item}} state=installed
  with_items:
    - git
    - unzip
    - python-pip

- pip:
     name: pip
     state: latest

- include: mysql.yml
- include: craft.yml
- include: nginx.yml
- include: php.yml

- name: Enable php mcrypt module
  command: phpenmod mcrypt

- service:
    name: php7.1-fpm
    state: restarted

- service:
    name: nginx
    state: restarted
