---
- name: Install MySQL packages
  apt: name={{item}} state=installed
  with_items:
    - mysql-server
    - libmysqlclient-dev

- pip: 
      name: MySQL-python

- name: Create craft database
  mysql_db: db=craft state=present

- name: Set craft mysql account and password
  mysql_user:
      name: "{{ mysql_user }}"
      host: localhost
      password: "{{ mysql_pass }}"
      priv: 'craft.*:ALL'
      state: present

- name: Fix Craft issue with MySQL 5.7+
  blockinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      insertafter: EOF
      content: "\ sql_mode = ''"
