---
- name: Add PHP Repository
  apt_repository: 
      repo='ppa:ondrej/php' 
      state=present
      update_cache=yes
  register: phpstable

- name: Install PHP packages
  apt: name={{item}} state=installed
  with_items:
    - php7.1
    - php7.1-fpm
    - php7.1-cli
    - php7.1-common
    - php7.1-curl
    - php7.1-gd
    - php7.1-mcrypt
    - php7.1-mysql
    - php7.1-mbstring
